# Generated by Django 5.2.4 on 2025-07-22 20:51

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.UUIDField()),
                ('recipe_name', models.CharField(max_length=50)),
                ('ingredients', models.JSONField()),
                ('source', models.CharField(max_length=50)),
                ('sections', models.CharField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('portion', models.IntegerField()),
                ('creator', models.CharField(max_length=50)),
                ('cook_time', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('image_links', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('steps', models.JSONField()),
                ('section_time', models.TimeField()),
                ('section_order', models.IntegerField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookingAPI.recipe')),
            ],
        ),
    ]
