# Generated by Django 5.2.4 on 2025-07-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='50')),
            ],
        ),
    ]
