# Generated by Django 5.2.4 on 2025-07-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0002_nationalities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nationalities',
        ),
    ]
