# Generated by Django 5.2.4 on 2025-07-28 01:08

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0004_nationality_type_remove_recipe_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='RecipeType',
        ),
        migrations.AddField(
            model_name='recipe',
            name='nationality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='CookingAPI.nationality'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(default=0, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
            preserve_default=False,
        ),
    ]
