# Generated by Django 5.2.4 on 2025-07-29 01:10

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0005_rename_type_recipetype_recipe_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 28, 21, 10, 29, 476218)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CookingAPI.nationality'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.UUIDField(default=uuid.UUID('14579b15-590b-4a33-8ca3-4e82d0c77e4e')),
        ),
    ]
