# Generated by Django 5.2.4 on 2025-07-28 22:36

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0005_rename_type_recipetype_recipe_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('list', models.JSONField()),
                ('time_test', models.TimeField()),
                ('int_list', models.CharField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
            ],
        ),
    ]
