# Generated by Django 5.2.4 on 2025-07-30 16:43

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0006_alter_recipe_cook_time_alter_recipe_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 12, 43, 17, 711081)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.UUIDField(default=uuid.UUID('45320b06-791a-47f9-b362-08e51ec9e06c')),
        ),
    ]
