# Generated by Django 5.2.4 on 2025-10-08 16:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0007_alter_recipe_cook_time_alter_recipe_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 12, 30, 32, 74428)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.UUIDField(default=uuid.UUID('e67db140-b807-4e8c-a0f9-08124c429127')),
        ),
        migrations.AlterField(
            model_name='recipesection',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='CookingAPI.recipe'),
        ),
    ]
