# Generated by Django 5.2.4 on 2025-10-16 20:31

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookingAPI', '0008_alter_recipe_date_created_alter_recipe_recipe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 16, 31, 34, 289558)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.UUIDField(default=uuid.UUID('77097eb6-9d4d-4ea6-b880-3806e0a6aadd')),
        ),
    ]
